library(RODBC) 
library(sqldf)
library(gsubfn)
library(proto)
library(RSQLite)
#odbcDataSources() 
conn=odbcConnect('testsql',uid='jzs',pwd='jzs')
result=sqlQuery(conn,'select*from tblEQIA_RPI_Basedata where fldsyear=2015') 
result2=sqldf("select max(flditemvalue) from result")
result2
odbcClose(conn) 